name: Maven and Docker Pipeline

on:
  push:
    branches:
      - main
      - pipelineTesting
  pull_request:
    branches:
      - main
      - pipelineTesting

jobs:
  pipeline: 
    runs-on: ubuntu-latest 

    steps: 
      #Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      #Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      #Set up Maven
      - name: Clean and Compile
        run: mvn clean compile

      #Set up MySQL
      - name: Install MySQL
        env:
          DB_DATABASE: revature
          DB_USER: root
          DB_PASSWORD: root
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD
        
      # Set up Kafka and Zookeeper
      - name: Install Kafka and Zookeeper
        run: |
          wget https://downloads.apache.org/kafka/3.5.0/kafka_2.13-3.5.0.tgz
          tar -xvf kafka_2.13-3.5.0.tgz
          mv kafka_2.13-3.5.0 kafka
          nohup kafka/bin/zookeeper-server-start.sh kafka/config/zookeeper.properties > /dev/null 2>&1 &
          nohup kafka/bin/kafka-server-start.sh kafka/config/server.properties > /dev/null 2>&1 &
          echo "Waiting for Kafka and Zookeeper to start..."
          sleep 20

      # Run tests
      - name: Run Tests
        env: 
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/revature?serverTimezone=UTC
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: revature
          SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
        run: mvn test

      # Clean Up Kafka, Zookeeper, and MySQL
      - name: Clean Up Services
        run: |
          sudo systemctl stop mysql
          kafka/bin/kafka-server-stop.sh
          kafka/bin/zookeeper-server-stop.sh
      
      #Package the JAR
      - name: Maven Package
        run: mvn package -DskipTests

      #Build Docker Image
      - name: Build Docker Image
        run: docker build -t brandonnguyenn/globetrotters:${{github.run_number}} -f docker-build/Dockerfile .

      #Login to Docker
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #Push Docker Image
      - name: Push Docker Image
        run: docker push brandonnguyenn/globetrotters:${{github.run_number}} .

      #Run Docker Container
      - name: Run Docker Containers
        # run: docker run -d -p 8081:8080 globetrotters/myapp:${{ github.run_number }}
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
        run: docker compose up -d

      # #Run Integration Tests
      # - name: Run Integration Tests
      #   run: mvn verify

      #Archive Artifacts
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: target/globetrotters-0.0.1-SNAPSHOT.jar
