name: Maven and Docker Pipeline

on:
  push:
    branches:
      - main
      - pipelineTesting
  pull_request:
    branches:
      - main
      - pipelineTesting

jobs:
  pipeline: 
    runs-on: ubuntu-latest 

    steps: 
      #Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      #Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      #Set up Maven
      - name: Clean and Compile
        run: mvn clean compile

      #Set up MySQL
      - name: Install MySQL
        run: |
              sudo apt-get update
              sudo apt-get install -y mysql-server  
              sudo systemctl start mysql

              # Reset the root password
              sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'revature';"
              sudo mysql -e "FLUSH PRIVILEGES;"

              # Create database and user
              sudo mysql -u root -p'revature' -e "CREATE DATABASE revature;"
              sudo mysql -u root -p'revature' -e "GRANT ALL PRIVILEGES ON revature.* TO 'root'@'%';"
              sudo mysql -u root -p'revature' -e "FLUSH PRIVILEGES;"
        
      # Set up Kafka and Zookeeper
      - name: Install Kafka and Zookeeper
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://downloads.apache.org/kafka/3.0.0/kafka_2.13-3.0.0.tgz
          tar -xzf kafka_2.13-3.0.0.tgz
          cd kafka_2.13-3.0.0
          nohup bin/zookeeper-server-start.sh config/zookeeper.properties &
          nohup bin/kafka-server-start.sh config/server.properties &
          echo "Kafka and Zookeeper are running in the background"
          sleep 20

      # Run tests
      - name: Run Tests
        env: 
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/revature?serverTimezone=UTC
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: revature
          SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
        run: mvn test

      # Clean Up Kafka, Zookeeper, and MySQL
      - name: Clean Up Services
        run: |
          sudo systemctl stop mysql
          kafka/bin/kafka-server-stop.sh
          kafka/bin/zookeeper-server-stop.sh
      
      #Package the JAR
      - name: Maven Package
        run: mvn package -DskipTests

      #Build Docker Image
      - name: Build Docker Image
        run: docker build -t brandonnguyenn/globetrotters:${{github.run_number}} -f docker-build/Dockerfile .

      #Login to Docker
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #Push Docker Image
      - name: Push Docker Image
        run: docker push brandonnguyenn/globetrotters:${{github.run_number}} .

      #Run Docker Container
      - name: Run Docker Containers
        # run: docker run -d -p 8081:8080 globetrotters/myapp:${{ github.run_number }}
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
        run: docker compose up -d

      # #Run Integration Tests
      # - name: Run Integration Tests
      #   run: mvn verify

      #Archive Artifacts
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: target/globetrotters-0.0.1-SNAPSHOT.jar
