name: Maven and Docker Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline: 
    runs-on: ubuntu-latest 

    steps: 
      #Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      #Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      #Set up Maven
      - name: Clean and Compile
        run: mvn clean compile

      #Package the JAR
      - name: Maven Package
        run: mvn package

      #Build Docker Image
      - name: Build Docker Image
        run: docker build -t globetrotters/myapp:${{ github.run_number }} -f docker-build/Dockerfile .

      #Login to Docker
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #Push Docker Image
      - name: Push Docker Image
        run: docker push globetrotters/myapp:${{ github.run_number }}

      #Run Docker Container
      - name: Run Docker Container
        run: docker run -d -p 8081:8080 globetrotters/myapp:${{ github.run_number }}

      #Archive Artifacts
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: target/globetrotters-0.0.1-SNAPSHOT.jar
